import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"
SHELL = "/bin/zsh"
EDITOR = "/opt/homebrew/bin/nvim"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

# opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font Mono"
size = 16
